version: '3'
services:
  web:
    build: docker
    container_name: grocasatest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
